### ISSUE TITLE
Any luck with Rails 3.2?

### ISSUE THREAD

**Issue by benjaminwood** [ngmoco/cache-money#32]
Has anybody had luck with Cache Money & Rails 3.2? Probably a long shot, but figured I'd ask.

Any help would be appreciated!

**Comment by ashleym1972** [comment]
No. When the database layer was refactored / replaced it made cache-money obsolete. Therefore the project is dead for newer versions of Rails.

**Comment by benjaminwood** [comment]
@ashleym1972, thank you so much for your response!

I had gathered that this was the general consensus, but I was hoping that somebody (like yourself) would confirm it for me. Thanks again!
